name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-otrs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file otrs/Dockerfile --tag demootrs-otrs:0.0.1
  
  build-mariadb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file mariadb/Dockerfile --tag demootrs-mariadb:0.0.1
